spring:
  datasource:
    url: jdbc:cassandra://localhost:9042
  main:
    allow-circular-references: true
cassandra:
  schema-action: create_if_not_exists
  local-datacenter: datacenter1
  contact-points: 127.0.0.1
  keyspace-name: pet_management_api

#logging:
#  level:
#    org:
#      apache: trace
#    springframework:
#      web: trace

jwt:
  secret: WzYwLCAtMTE0LCAtMTI4LCAtMTIsIC0xMjgsIDExLCAtODgsIC0xMjAsIDEwNywgMzMsIDY0LCA1OSwgLTcsIDY5LCAxMCwgLTk4LCAtNzUsIDEyMywgMjIsIC0zNSwgNzcsIC0xMTYsIDExMywgOTgsIDExNSwgLTk5LCAtNjMsIC01MiwgMTExLCAtNzMsIC0xMTcsIDQzXQ==